using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Raymark.Caching
{
    public enum CacheTypeEnum
    {
        Entity = 0,
        ActiveAssociatesForManager,
        ActivityTask,
        Address,
        AddressType,
        ApplicationModuleDefList,
        CommunicationType,
        ContactChannel,
        ContactSourceType,
        ConfigSettingsForSaks,
        Country,
	    DiscountCriteria,
		DefaultLandingPageLayout,
        Province,
        Customer,
        Customer12monthSpendWithAssociate,
        Customer12monthSpendTotal,
        Customer2Staff,
        StaffCommunication,
        CustomerCommunication,
        CustomerCommunicationHistory,
        CustomerCommunicationTemplate,
        CustomerCommunicationTemplateList,
        CustomerCommunicationTemplateListDefault,
        CustomerCommunicationTemplateType,
        CustomerCurrentOfferList,
        CustomerDate,
        CustomerDateType,
        CustomerFeatureItemsCount,
        CustomerIdentification,
        CustomerNote,
        CustomerRelationship,
        CustomerRelationshipType,
        //CustomerVipFacStatus,
        CustomerWishList,
        EmailType,
        GroupAccessPermission,
        GroupAccessPermissionList,
        IsClientCoBrand,
        ItemStatus,
        Language,
        LandingPageLayout,
        LastXTransactions,
        LastXTransactionsInfo,
        NamePrefix,
        Gender,
        ClientDisplayColumn,
        OtherAddressCategory,
        Parameter,
        PointsEvent,
        Product,
        ProductCategories,
        ProductGroup,
        ProductGroupLevel1List,
        ProductGroupLevel2List,
        ProductImageUrls,
        ReportParamType,
        SecurityPermission,
        Staff,
        Store,
        Tax,
        TaxRegion,
		TaxInfoList,
        TelephoneType,
        AllTelephoneType,
        TerminatedAssociatesForManager,
        TransactionLineItemsHistory,
        TransactionsHistory,
        TransactionSummary,
        TransactionSummaryForSaksFirst,
        WishListProductInfo,
        Brand,
        BrandAlert,
        CampaignList,
        Campaign,
        QueryList,
        CustomerTransactionSummary,
        LastXTransaction, //added
        CustomerLastTransaction,
        CustomerTransactionWeightByItemType,
        ProductTopCategory,
        CustomerTransaction,
        CustomerTransactionDetail,
        TransactionSumarryByDivision,
        StaffListForManager,
        QueryRules,
        Preference,
        CustomerCommunicationTemplateCategory,
        CustomerWishListForToken,
        GetCustomerAttributesWithValues,
        StaffTasks,
        CustomerType,
        TransactionSummaryByDivisionLabel,
        CustomerImageType
    }
}
